# Generated by Django 2.0 on 2018-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_backend', '0005_auto_20180319_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='emoji_checked',
            field=models.IntegerField(default=0),
        ),
    ]
