# Generated by Django 2.0 on 2018-03-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('name', models.CharField(default=None, max_length=20)),
                ('image', models.CharField(default=None, max_length=100)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airdate', models.DateField()),
                ('airtime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sent_frontend.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sent_frontend.Program'),
        ),
    ]
