# Generated by Django 2.0 on 2018-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
