# Generated by Django 2.0 on 2018-03-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sent_frontend', '0002_auto_20180326_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('tweet_id', models.BigIntegerField()),
                ('url', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('replies', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('hashtags', models.CharField(max_length=200)),
                ('sentiment', models.IntegerField(default=None, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sent_frontend.Episode')),
            ],
        ),
    ]
