# Generated by Django 2.0 on 2018-03-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_frontend', '0003_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.IntegerField(default=99, null=True),
        ),
    ]
